language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - SOLR_VERSION=3.5.0
  - SOLR_VERSION=3.6.2

before_script:
  - composer install --prefer-dist --dev
  - curl -L https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | bash

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
